name: Generate & Publish Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*.cs'
      - 'docs/**'
      - '.github/workflows/publish_doc.yml'
  workflow_dispatch:

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Build project (for XML documentation)
        run: |
          dotnet restore
          dotnet build --configuration Release

      - name: Install DocFX
        run: dotnet tool install --global docfx

      - name: Generate documentation
        run: |
          if [ ! -f "docfx.json" ]; then
            docfx init -q
          fi
          docfx build

      - name: Generate class diagram
        run: |
          mkdir -p docs
          cat > docs/class-diagram.puml << EOF
          @startuml
          abstract class Employee {
            +Name: string
            +Salary: decimal
            +Accept(visitor: IEmployeeVisitor): string
          }

          interface IEmployeeVisitor {
            +VisitDeveloper(dev: Developer): string
            +VisitManager(mgr: Manager): string
          }

          class Developer {
            +ProgrammingLanguage: string
          }

          class Manager {
            +TeamSize: int
          }

          class ReportVisitor

          Employee <|-- Developer
          Employee <|-- Manager
          IEmployeeVisitor <|.. ReportVisitor
          EOF

          sudo apt-get update && sudo apt-get install -y graphviz default-jre
          wget https://github.com/plantuml/plantuml/releases/download/v1.2023.13/plantuml-1.2023.13.jar
          java -jar plantuml-1.2023.13.jar docs/class-diagram.puml -o _site/images

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site