name: Publish Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*.cs'
      - 'docs/**'
      - 'docfx.json'
      - '.github/workflows/publish_doc.yml'
  workflow_dispatch:

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project (generates XML documentation)
        run: dotnet build --configuration Release --no-restore

      - name: Install DocFX
        run: dotnet tool install --global docfx

      - name: Generate API documentation with DocFX
        run: |
          if [ -f "docfx.json" ]; then
            echo "✅ Using existing docfx.json"
            docfx metadata docfx.json
            docfx build docfx.json
          else
            echo "⚠️  No docfx.json found, creating default configuration"
            docfx init -q -o .
            docfx metadata
            docfx build
          fi

      - name: Install PlantUML dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre graphviz
          wget -q https://github.com/plantuml/plantuml/releases/download/v1.2024.3/plantuml-1.2024.3.jar -O plantuml.jar

      - name: Generate class diagram from PlantUML
        run: |
          if [ -f "docs/class-diagram.puml" ]; then
            echo "✅ Found existing class-diagram.puml"
            mkdir -p _site/diagrams
            java -jar plantuml.jar -tpng docs/class-diagram.puml -o ../_site/diagrams
          else
            echo "⚠️  No class-diagram.puml found, creating default diagram"
            mkdir -p docs _site/diagrams
            cat > docs/class-diagram.puml << 'EOF'
@startuml
skinparam classAttributeIconSize 0
skinparam backgroundColor #FEFEFE
skinparam classBackgroundColor #E8F5E9
skinparam classBorderColor #4CAF50

title Employee Management System - Visitor Pattern

interface IEmployeeVisitor {
  +VisitDeveloper(Developer): string
  +VisitManager(Manager): string
}

abstract class Employee {
  +Name: string
  +Salary: decimal
  +{abstract} Accept(IEmployeeVisitor): string
}

class Developer {
  +ProgrammingLanguage: string
  +Accept(IEmployeeVisitor): string
}

class Manager {
  +TeamSize: int
  +Accept(IEmployeeVisitor): string
}

class ReportVisitor {
  +VisitDeveloper(Developer): string
  +VisitManager(Manager): string
}

class EmployeeExtensions <<static>> {
  +{static} GenerateReport(Employee): string
}

Employee <|-- Developer
Employee <|-- Manager
IEmployeeVisitor <|.. ReportVisitor
Developer ..> IEmployeeVisitor : uses
Manager ..> IEmployeeVisitor : uses
EmployeeExtensions ..> ReportVisitor : creates

note right of IEmployeeVisitor
  Visitor Pattern:
  Separates operations
  from object structure
end note

@enduml
EOF
            java -jar plantuml.jar -tpng docs/class-diagram.puml -o ../_site/diagrams
          fi

      - name: Create documentation landing page
        run: |
          cat > _site/index.html << 'EOF'
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EmployeeLib - Documentation</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 20px;
        }
        .container { max-width: 1200px; margin: 0 auto; }
        header {
            background: white;
            border-radius: 20px;
            padding: 50px;
            margin-bottom: 30px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.15);
            text-align: center;
        }
        h1 {
            color: #667eea;
            font-size: 3em;
            margin-bottom: 15px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }
        .subtitle { color: #666; font-size: 1.3em; font-weight: 300; }
        .grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
            gap: 25px;
            margin-bottom: 30px;
        }
        .card {
            background: white;
            border-radius: 20px;
            padding: 35px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.1);
            transition: all 0.3s ease;
        }
        .card:hover {
            transform: translateY(-10px);
            box-shadow: 0 20px 60px rgba(0,0,0,0.2);
        }
        .card-icon { font-size: 3em; margin-bottom: 15px; }
        .card h2 { color: #333; margin-bottom: 15px; font-size: 1.6em; }
        .card p { color: #666; line-height: 1.8; margin-bottom: 25px; }
        .btn {
            display: inline-block;
            padding: 15px 35px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            text-decoration: none;
            border-radius: 30px;
            font-weight: 600;
            transition: all 0.3s ease;
        }
        .btn:hover {
            transform: scale(1.05);
            box-shadow: 0 8px 25px rgba(102, 126, 234, 0.5);
        }
        .diagram-section {
            background: white;
            border-radius: 20px;
            padding: 40px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.1);
        }
        .diagram-section h2 { color: #333; margin-bottom: 25px; font-size: 2em; }
        .diagram-section img {
            width: 100%;
            height: auto;
            border-radius: 15px;
            box-shadow: 0 5px 20px rgba(0,0,0,0.1);
        }
        .features {
            background: white;
            border-radius: 20px;
            padding: 40px;
            margin-top: 30px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.1);
        }
        .features h3 { color: #667eea; margin-bottom: 20px; font-size: 1.5em; }
        .features ul { list-style: none; padding: 0; }
        .features li {
            padding: 12px 0;
            color: #666;
            font-size: 1.1em;
            border-bottom: 1px solid #f0f0f0;
        }
        .features li:before {
            content: "✓ ";
            color: #4CAF50;
            font-weight: bold;
            margin-right: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>📚 EmployeeLib Documentation</h1>
            <p class="subtitle">Employee Management System with Visitor Pattern</p>
        </header>

        <div class="grid">
            <div class="card">
                <div class="card-icon">📖</div>
                <h2>API Documentation</h2>
                <p>Complete API documentation generated with DocFX. Explore all classes, methods, and properties.</p>
                <a href="api/index.html" class="btn">View Documentation</a>
            </div>

            <div class="card">
                <div class="card-icon">📊</div>
                <h2>Code Coverage</h2>
                <p>Detailed code coverage report from unit tests. See which parts of the code are tested.</p>
                <a href="../coverage/index.html" class="btn">View Coverage</a>
            </div>

            <div class="card">
                <div class="card-icon">🔧</div>
                <h2>Visitor Pattern</h2>
                <p>Implementation of the Visitor design pattern to separate operations from object structure.</p>
                <a href="#diagram" class="btn">View Diagram</a>
            </div>
        </div>

        <div class="features">
            <h3>✨ Project Features</h3>
            <ul>
                <li>Visitor Pattern correctly implemented</li>
                <li>Unit tests with xUnit</li>
                <li>Automated code coverage</li>
                <li>Documentation generated with DocFX</li>
                <li>UML class diagrams</li>
                <li>CI/CD with GitHub Actions</li>
                <li>Automatic deployment to GitHub Pages</li>
            </ul>
        </div>

        <div class="diagram-section" id="diagram">
            <h2>📐 UML Class Diagram</h2>
            <p style="color: #666; margin-bottom: 25px;">
                Visual representation of the system structure using the Visitor pattern.
                This diagram shows relationships between Employee, Developer, Manager, and the Visitor.
            </p>
            <img src="diagrams/class-diagram.png" alt="UML Class Diagram">
        </div>
    </div>
</body>
</html>
EOF

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site